spring:
  application:
    name: spring-cloud-eureka-cus
server:
  port: 8912
eureka:
#  instance:
#    hostname: peer3
  client:
    #registerWithEureka 和 fetchRegistry 设置为false，表明自己属于服务中心主体
    registerWithEureka: true #是否将自己注册到eureka server，构建集群环境时，需将自己注册到集群中，默认为true
    fetchRegistry: true #是否从eureka server获取注册信息，构建集群环境时，需同步其他eureka server节点，默认为true
    serviceUrl:
      defaultZone: http://127.0.0.1:8910/eureka/

#打开Feign的Hystrix熔断功能
feign:
  hystrix:
    enabled: false

#设置Hystrix的time-out时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
        timeout:
          enabled: false

zuul:
  routes:
    api:
      path: /api/**
      serviceId: spring-cloud-eureka-pro


  retryable: true #是否开启重试功能


ribbon:
  MaxAutoRetries: 2 #对当前服务的重试次数
  MaxAutoRetriesNextServer: 1 #切换相同Server实例的次数
  ConnectTimeout: 250 #ribbon重试超时时间
  ReadTimeout: 1000 #建立连接后的超时时间